version: "3.4"
name: myapi-mariadb-dev
services:
  mariadb:
    image: mariadb:11.2.6
    container_name: mariadb-dev
    restart: always
    env_file: ./.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - $MARIADB_PORT:$MARIADB_PORT
    healthcheck:
      test: [ CMD, healthcheck.sh, --connect, --innodb_initialized]
      interval: 5s
      timeout: 3s
      retries: 3